### ISSUE TITLE
Generación de requirements_string

### ISSUE THREAD

**Issue by Michotastico** [cadcc/malla-dcc#2]
https://github.com/cadcc/malla-dcc/blob/688897fb6c7d8a81ea1a61688e0c42c58e9a24f4/html_render/renderer.py#L36

Creo que la optimización que te puede servir es la siguiente. Ya que en verdad no hay necesidad de pasar la lista a string para luego formatearla, cuando en verdad ya puedes iterar sobre ella y darle el estilo necesario y luego hacerle join para tener el string :smile: .

```python
requirements = map(
	lambda req: '"{}"'.format(req),
	ramo.get('requisitos', [])
)

requirements_string = ','.join(requirements)
```

**Comment by sleivav** [comment]
Muchas gracias! Ya lo cambié <3
